name = "kanae-real-estate"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "20"
NEXT_TELEMETRY_DISABLED = "1"
